"""
Experiment a)
--- Fixed q, vary noise scale
--- Compare:
--- --- Var_unbiased Laplace
--- --- Var_unbiased Gaussian
--- --- Var_naive Laplace
--- --- Var_naive Gaussian
--- This reveals different tail behaviors of the noise distributions, 
    and how they affect the variance of the unbiased estimator, 
    compared to the naive estimator.

Experiment b)
--- Fixed noise scale, vary q
--- Reveals how the variance of the estimators changes 
    with the magnitude of the query output.

Experiment c)
--- Fixed polynomial, compare Laplace and Gaussian noise
--- This answers, which noise dist. yields better unbiased
    estimator performance for a given polynomial.

Repeat for MSE instead of variance, to see the bias-variance tradeoff.
"""
from os import path

import sympy as sp
import numpy as np
import os

from dp_estimators import EstimatorSystem
from noise_models import LaplaceNoiseModel, GaussianNoiseModel
from plotting.utility_plotting import (
        format_value,
        metric_expr_estimators,
        evaluate_on_grid,
        plot_curves
)

METRIC_LABELS = {
    "variance": "Variance",
    "mse": "MSE",
}

#----------------------------------------------------------------------
# Symbolic Setup
#----------------------------------------------------------------------
def build_system(noise_model="laplace"):
    """
    Build the EstimatorSystem with the desired noise models and symbols. 
    Input: None
    Output: Two tuples (system, symbols), where
    - system is an instance of EstimatorSystem, initialized with the desired noise
      model and symbols
    - symbols is a dictionary of sympy symbols used in the system
    """
    q = sp.symbols("q", positive=True, real=True)
    X = sp.symbols("X", positive=True, real=True)

    if noise_model == "laplace":
        Delta = sp.symbols("Delta", positive=True, real=True)
        epsilon = sp.symbols("epsilon", positive=True, real=True)

        system = EstimatorSystem(
            noise_model=LaplaceNoiseModel(delta=Delta, epsilon=epsilon),
            q=q,
            x=X
        )
        symbols = {"Delta": Delta, "epsilon": epsilon, "q": system.q, "X": system.x}

    elif noise_model == "gaussian":
        sigma = sp.symbols("sigma", positive=True, real=True)

        system = EstimatorSystem(
            noise_model=GaussianNoiseModel(sigma=sigma),
            q=q,
            x=X
        )
        symbols = {"sigma": sigma, "q": system.q, "X": system.x}

    else:
        raise ValueError(f"Unsupported noise model: {noise_model}")
    
    return system, symbols

def symbolic_poly_reports(system, polynomials):
    """
    Generate symbolic reports for a list of polynomials, using the given EstimatorSystem.
    Input:
    - system: an instance of EstimatorSystem, initialized with the desired noise
      model and symbols
    - polynomials: a list of tuples (name, f), where name is a string identifier 
      for the polynomial, and f is a sympy expression for the polynomial function of q.
    Output:
    - A dictionary mapping each polynomial name to its symbolic report 
      generated by the system's compare method
    """
    reports = {}
    for name, f in polynomials.items():

        # The following is to avoid issues with sympy not recognizing the symbol
        # "q" in the symbolic expressions,whic can happen with wrong symbols. 
        f = sp.sympify(f)
        # Replace any symbol named "q" with system.q.
        for sym in f.free_symbols:
            if sym.name == "q":
                f = f.subs(sym, system.q)

        reports[name] = system.compare(f=f)
    return reports

def build_reports(polynomials):
    """
    Build the EstimatorSystem's and generate symbolic reports for the given polynomials.
    Input:
    - polynomials: a list of tuples (name, f), where name is a string identifier 
      for the polynomial, and f is a sympy expression for the polynomial function of q.
    Output:
    - A dictionary mapping the noise models, "laplace" and "gaussian", to their respective 
        dictionaries of symbolic reports and their symbols. Specifically, the output is a tuple of two dictionaries:
        - The first dictionary maps each noise model ("laplace" and "gaussian") to its respective dictionary of symbolic report.
        - The second dictionary maps each noise model to its respective dictionary of sympy symbols used in the system.

    """
    laplace_system, laplace_symbols = build_system(noise_model="laplace")
    gaussian_system, gaussian_symbols = build_system(noise_model="gaussian")

    laplace_reports = symbolic_poly_reports(laplace_system, polynomials)
    gaussian_reports = symbolic_poly_reports(gaussian_system, polynomials)

    return {
        "laplace": laplace_reports,
        "gaussian": gaussian_reports
    }, {
        "laplace": laplace_symbols,
        "gaussian": gaussian_symbols
    }

def base_subs_for_noise(
        noise_dist, 
        symbols, 
        *, 
        q_value=None, 
        Delta_value=None, 
        epsilon_value=None
):
    """
    Build substitution dicts for Gaussian or Laplace noise. 
    For Gaussian, epsilon is introduced via the relation: 
        sigma = sqrt(2) * Delta / epsilon, 
    as it is not an inherent parameter ot this noise distribution. 

    If epsilon_value is None, sigma remains symbolic in epsilon
    (for plotting over epsilon on the x-axis). 

    Input: 
    - noise_dist: a string, either "laplace or "gaussian", 
    - symbols: the dictionary of symbols ordered by noise distribution, 
      as returned by the build_reports function, i.e., symbols_by_noise_dist
    - q_value: a specific value of q to substitute (if not None)
    - Delta_value: a specific value of Delta to substitute (if not None)
    - epsilon_value: a specific value of epsilon to substitute (if not None)
    Output:
    - A dictionary of substitutions to apply to the symbolic expressions for the given noise distribution.
    """
    if noise_dist == "laplace":
        subs = {}
        if q_value is not None:
            subs[symbols[noise_dist]["q"]] = q_value
        if Delta_value is not None:
            subs[symbols[noise_dist]["Delta"]] = Delta_value
        if epsilon_value is not None:            
            subs[symbols[noise_dist]["epsilon"]] = epsilon_value

    elif noise_dist == "gaussian":
        subs = {}
        if q_value is not None:
            subs[symbols[noise_dist]["q"]] = q_value

        if Delta_value is not None:
            if epsilon_value is None:
                # the value epsilon is inherent in Gaussian dist
                epsilon_symbol = symbols["laplace"]["epsilon"]
                subs[symbols[noise_dist]["sigma"]] = sp.sqrt(2) * Delta_value / epsilon_symbol
            else:
                subs[symbols[noise_dist]["sigma"]] = sp.sqrt(2) * Delta_value / epsilon_value
    else:
        raise ValueError(f"Unsupported noise distribution: {noise_dist}")
    return subs

#----------------------------------------------------------------------
# Curve Builders
#----------------------------------------------------------------------
def curves_direct_for_fixed_poly_and_q(
        reports,
        symbols,
        name,
        metric,
        q_value,
        Delta_value,
        eps_grid
):
    """
    One plot for a fixed polynomial and fixed q.
    Curves are:
        Laplace naive
        Laplace unbiased
        Gaussian naive
        Gaussian unbiased

    X-axis is epsilon.
    """
    out = {}
    epsilon_symbol = symbols["laplace"]["epsilon"]

    for noise_dist in ["laplace", "gaussian"]:
        for estimator in ["naive", "unbiased"]:
            expr = metric_expr_estimators(
                reports_by_label=reports[noise_dist],
                label=name,
                estimator=estimator,
                metric=metric,
            )

            subs = base_subs_for_noise(
                noise_dist=noise_dist,
                symbols=symbols,
                q_value=q_value,
                Delta_value=Delta_value,
            )

            label = f"{noise_dist.capitalize()} {estimator}"

            out[label] = evaluate_on_grid(
                expr,
                epsilon_symbol,
                eps_grid,
                subs,
            )

    return out

def curves_direct_for_fixed_poly_and_epsilon(
        reports, 
        symbols, 
        name, 
        metric,
        epsilon_value,
        Delta_value, 
        q_grid   
):
    """
    One plot for a fixed polynomial and fixed epsilon.
    Curves are:
        Laplace naive
        Laplace unbiased
        Gaussian naive
        Gaussian unbiased

    x-axis is q.
    """
    out = {}

    for noise_dist in ["laplace", "gaussian"]:
        q_symbol = symbols[noise_dist]["q"]

        for estimator in ["naive", "unbiased"]:
            expr = metric_expr_estimators(
                reports_by_label=reports[noise_dist],
                label=name,
                estimator=estimator,
                metric=metric,
            )

            subs = base_subs_for_noise(
                noise_dist=noise_dist,
                symbols=symbols,
                Delta_value=Delta_value,
                epsilon_value=epsilon_value,
            )

            label = f"{noise_dist.capitalize()} {estimator}"

            out[label] = evaluate_on_grid(
                expr,
                q_symbol,
                q_grid,
                subs,
            )
    return out
#----------------------------------------------------------------------
# Main
#----------------------------------------------------------------------
def plot_plots(
    *,
    q_values,
    q_range,
    epsilon_values,
    epsilon_range,
    polynomials,
    Delta_values,
    metrics,
    each_plot,
    path_for_plots
):
    reports, symbols = build_reports(polynomials)

    eps_grid = np.linspace(epsilon_range[0], epsilon_range[1], 300)
    q_grid = np.linspace(q_range[0], q_range[1], 300)

    names = list(polynomials.keys())

    for metric in metrics:
        y_label = METRIC_LABELS[metric]

        if "direct_by_q_and_poly" in each_plot:
            for name in names:
                for q_value in q_values:
                    for Delta_value in Delta_values:
                        curves = curves_direct_for_fixed_poly_and_q(
                            reports=reports,
                            symbols=symbols,
                            name=name,
                            metric=metric,
                            q_value=q_value,
                            Delta_value=Delta_value,
                            eps_grid=eps_grid,
                        )

                        title = (
                            f"{y_label} vs ε for {format_value(name)}, "
                            f"q={format_value(q_value)}, "
                            f"Δ={format_value(Delta_value)}, "
                            f"variance-matched Gaussian"
                        )

                        save_path = os.path.join(
                            path_for_plots,
                            "direct_by_q_and_poly",
                            metric,
                        )

                        plot_curves(
                            x_label="ε",
                            y_label=y_label,
                            x_grid=eps_grid,
                            y_data=curves,
                            title=title,
                            save_path=save_path,
                            yscale="log"
                        )
        if "direct_by_epsilon_and_poly" in each_plot: 
            for name in names:
                for epsilon_value in epsilon_values:
                    for Delta_value in Delta_values:
                        curves = curves_direct_for_fixed_poly_and_epsilon(
                            reports=reports,
                            symbols=symbols,
                            name=name,
                            metric=metric,
                            epsilon_value=epsilon_value,
                            Delta_value=Delta_value,
                            q_grid=q_grid,
                        )

                        title = (
                            f"{y_label} vs q for {format_value(name)}, "
                            f"ε={format_value(epsilon_value)}, "
                            f"Δ={format_value(Delta_value)}, "
                            f"variance-matched Gaussian"
                        )

                        save_path = os.path.join(
                            path_for_plots,
                            "direct_by_epsilon_and_poly",
                            metric,
                        )

                        plot_curves(
                            x_label="q",
                            y_label=y_label,
                            x_grid=q_grid,
                            y_data=curves,
                            title=title,
                            save_path=save_path,
                        )
