import os
from pathlib import Path

import matplotlib
matplotlib.use("TkAgg") # Use the TkAgg backend for interactive plotting
import matplotlib.pyplot as plt

import numpy as np
import sympy as sp

from dp_estimators import EstimatorSystem
from noise_models import LaplaceNoiseModel

METRIC_LABELS = {
    "variance_ratio": "Variance Ratio",
    "variance_relative": "Variance Relative",
    "mse_ratio": "MSE Ratio",
    "mse_relative": "MSE Relative"
}

#----------------------------------------------------------------------
# Symbolic Setup
#----------------------------------------------------------------------

def build_system():
    """
    Function initializes the EstimatorSystem with a Laplace noise model, using symbolic variables for Delta, epsilon, q, and X.
    This allows for symbolic analysis of the estimators and their properties as functions of these parameters. 
    Input: 
    - None (the symbolic variables are defined within the function)
    Output:
    - system: an instance of EstimatorSystem initialized with the Laplace noise model and symbolic variables
    - {"Delta": Delta, "epsilon": epsilon, "q": q, "X": X}: a dictionary of the symbolic variables used in the system.
    """
    Delta = sp.Symbol("Delta", real=True, positive=True)
    epsilon = sp.Symbol("epsilon", real=True, positive=True)
    q = sp.Symbol("q", real=True)
    X = sp.Symbol("X", real=True)

    system = EstimatorSystem(
        noise_model=LaplaceNoiseModel(delta=Delta, epsilon=epsilon),
        q=q,
        x=X
    )
    return system, {"Delta": Delta, "epsilon": epsilon, "q": q, "X": X}

def symbolic_chebyshev_reports(system, q_symbol, chebyshev_degrees):
    """
    Function takes an EstimatorSystem, a symbolic variable 
    for q, and a list of Chebyshev degrees, and computes the comparison reports for 
    the unbiased estimator corresponding to the Chebyshev polynomial of each degree.
    reports_by_degree is the report returned by system.compare().
    Input:
    - system: an instance of EstimatorSystem, which contains the noise model and the symbolic variables
    - q_symbol: the symbolic variable representing q in the system
    - chebyshev_degrees: a list of integers representing the degrees of the 
        Chebyshev polynomials to analyze
    Output:
    - reports_by_degree: a dictionary mapping each degree n to the report 
    generated by system.compare() for the Chebyshev polynomial of degree n. 
    Each report contains the symbolic expressions for the variance and MSE 
    of the unbiased estimator corresponding to the Chebyshev polynomial 
    of that degree.
    """
    reports_by_degree = {}
    for n in chebyshev_degrees:
        f = sp.chebyshevt(n, q_symbol)
        report = system.compare(f=f)
        reports_by_degree[n] = report

    return reports_by_degree


def build_reports(chebyshev_degrees):
    """
    Function uses the build_system functions to initialize the 
    system with the specified symbolic variables, and the calls symbolic_chebyshev_reports
    to compute the reports for the specified Chebyshev degrees.
    It basically combines the system initialization and the report generation.
    Input:
    - chebyshev_degrees: a list of integers representing the degrees of the Chebyshev polynomials to analyze
    Output:
    - reports_by_degree: a dictionary mapping each degree n to the report generated by system.compare()
    - symbols: a dictionary of the symbolic variables used in the system
    """
    system, symbols = build_system()
    reports_by_degree = symbolic_chebyshev_reports(
        system=system,
        q_symbol=symbols["q"],
        chebyshev_degrees=chebyshev_degrees
    )
    return reports_by_degree, symbols

#----------------------------------------------------------------------
# Expression Evaluation
#----------------------------------------------------------------------

def metric_expr(reports_by_degree, degree, metric):
    """
    Function to extract the symbolic expression for a given metric (e.g., 
    "variance_ratio") from the report for a specific degree of Chebyshev polynomial.
    Input:
    - reports_by_degree: a dictionary mapping each degree n to the report generated by system.compare()
    - degree: the specific degree of Chebyshev polynomial for which to extract the metric expression
    - metric: a string indicating which metric to extract from the report (e.g., "variance_ratio", "mse_relative", etc.)
    Output:
    - The symbolic expression corresponding to the specified metric for the given degree of Chebyshev polynomial.
    """
    return reports_by_degree[degree][metric]

def evaluate_on_grid(expr, x_symbol, x_grid, subs_dict):
    """
    Function to evaluate a symbolic expression over a grid of values for 
    a specific variable.
    Input:
    - expr: the symbolic expression to evaluate
    - x_symbol: the symbolic variable in the expression, that are to be the x-axis
    - x_grid: a list of values to evaluate the expression at
    - subs_dict: a dictionary of other variable substitutions to apply
    Output:
    - A dictionary mapping each value in the grid to the evaluated 
    result of the expression.
    """
    eval_expr = sp.simplify(expr.subs(subs_dict))
    eval_func = sp.lambdify(x_symbol, eval_expr, modules=["numpy"])
    y = eval_func(x_grid)

    y = np.asarray(y, dtype=float)

    if y.shape == (): 
        # scalar output, make it an array of the same shape as x_grid
        y = np.full_like(x_grid, fill_value=float(y), dtype=float)
    elif y.shape == (1,):
        # length - 1 array
        y = np.full_like(x_grid, fill_value=float(y[0]), dtype=float)
    # clean inf/nan for plotting
    y[~np.isfinite(y)] = np.nan
    return y

def format_value(value):
    """
    Utility function to format a value for display in plot labels.
    If the value is a sympy expression, it converts it to a string.
    If the value is a float, it formats it to 3 significant digits.
    Otherwise, it converts it to a string directly.
    Input:
    - value: the value to format, which can be a sympy expression, a float,
    or any other type.
    Output:
    - A string representation of the value, formatted appropriately for 
    display in plot labels. 
    """
    if isinstance(value, sp.Basic):
        return F"{float(value):.3g}"
    if isinstance(value, float):
        return f"{value:.3g}"
    else: 
        return str(value)

# ----------------------------------------------------------------------
# Curve Builders
# ----------------------------------------------------------------------

def curves_q_for_fixed_degree(
        reports_by_degree, 
        degree, 
        q_values, 
        metric, 
        epsilon_symbol, 
        eps_grid, 
        q_symbol, 
        base_subs
):
    """
    One plot for a fixed degree.
    Curves vary by q.
    X-axis is epsilon.
    """
    out = {}
    expr = metric_expr(reports_by_degree, degree, metric)

    for q_value in q_values:
        subs = dict(base_subs) # make a copy of the base substitutions, to avoid modifying the original
        subs[q_symbol] = q_value
        label = f"q = {format_value(q_value)}"
        out[label] = evaluate_on_grid(expr, epsilon_symbol, eps_grid, subs)
    
    return out

def curves_degree_for_fixed_q(
        reports_by_degree, 
        degree_values, 
        q_value, 
        metric, 
        epsilon_symbol, 
        eps_grid, 
        q_symbol, 
        base_subs
):
    """
    One plot for a fixed q.
    Curves vary by degree.
    X-axis is epsilon.
    """
    out = {}
    subs = dict(base_subs) # make a copy of the base substitutions, to avoid modifying the original
    subs[q_symbol] = q_value

    for degree in degree_values:
        expr = metric_expr(reports_by_degree, degree, metric)
        label = f"Degree {format_value(degree)}"
        out[label] = evaluate_on_grid(expr, epsilon_symbol, eps_grid, subs)
    
    return out

def curves_epsilon_for_fixed_degree(
        reports_by_degree,
        degree, 
        epsilon_values, 
        metric, 
        q_symbol, 
        q_grid, 
        epsilon_symbol,
        base_subs
):
    """
    One plot for a fixed degree.
    Curves vary by epsilon.
    X-axis is q.
    """
    out = {}
    expr = metric_expr(reports_by_degree, degree, metric)

    for epsilon_value in epsilon_values:
        subs = dict(base_subs) # make a copy of the base substitutions, to avoid modifying the original
        subs[epsilon_symbol] = epsilon_value
        label = f"epsilon = {format_value(epsilon_value)}"
        out[label] = evaluate_on_grid(expr, q_symbol, q_grid, subs)
    
    return out

# ----------------------------------------------------------------------
# Plotting
# ----------------------------------------------------------------------

def add_reference_line(y_label, ax=None):
    """
    FUnction to add a reference line to the plot, indicating the threshold 
    for the metric being plotted. For the ratio metrics, the threshold is 1, 
    indicating where the unbiased estimator has the same variance/MSE as 
    the naive estimator. For the relative metrics, the threshold is 0, 
    indicating where the unbiased estimator has the same variance/MSE as 
    the naive estimator. The function also adds text labels to indicate 
    which side of the line corresponds to which estimator being better.
    Input:
    - x_grid: the grid of x values for the plot, used to position the text
    - y_label: the label for the y-axis, indicating the metric being plotted
    Output:
    - None 
    """
        # check if only one of the text-boxes stays within the y-limits of the plot
        # (hence the threshold line is either close to the top or bottom of the plot, 
        # or not in the plot at all, and only one of the two sides of the line is visible), 
        # in this case, add only the text-box, that corresponds to the side of the line that is visible, 
        # and let plt decide where to place it (so it won't be cut off by the limits of the plot).
    if ax is None:
        ax = plt.gca()
    
    if y_label in {"Variance Ratio", "MSE Ratio"}:
        threshold = 1.0
    elif y_label in {"Relative Variance", "Relative MSE", "Variance Relative", "MSE Relative"}:
        threshold = 0.0
    else:
        return

    ax.axhline(threshold, color="black", linestyle="--", linewidth=1)
    ymin, ymax = ax.get_ylim()
    x_frac = 0.08

    # threshold position measured in the visible axis box
    y_frac = (threshold - ymin) / (ymax - ymin)

    # threshold below visible area
    if y_frac < 0:
        ax.text(
            x_frac, 0.15, "Naive lower",
            transform=ax.transAxes,
            ha="left", va="bottom", fontsize=9, color="black"
        )
        return

    # threshold above visible area
    if y_frac > 1:
        ax.text(
            x_frac, 0.85, "Unbiased lower",
            transform=ax.transAxes,
            ha="left", va="top", fontsize=9, color="black"
        )
        return

    # threshold is visible: add only labels that fit
    pad_frac = 0.04

    if y_frac + 2*pad_frac < 1:
        ax.text(
            x_frac, y_frac + pad_frac, "Naive lower",
            transform=ax.transAxes,
            ha="left", va="bottom", fontsize=9, color="black"
        )

    if y_frac - 2*pad_frac > 0:
        ax.text(
            x_frac, y_frac - pad_frac, "Unbiased lower",
            transform=ax.transAxes,
            ha="left", va="top", fontsize=9, color="black"
        )

def save_filename(text):
    """
    Generate a safe filename from the given text.
    """
    return (
        text.replace("$", "")
        .replace("\\", "")
        .replace("=", "")
        .replace(",", "")
        .replace(" ", "_")
        .replace("/", "_over_")
        .replace("Variance", "Var")
        .replace("Relative", "Rel")
        .replace("Chebyshev", "Cheb")
    )

def plot_curves(x_label, y_label, x_grid, y_data, title=None, path=None):
    """
    Plot the curves for the given x and y data.
    """
    plt.figure(figsize=(10, 6))
    for label, y_values in y_data.items():
        plt.plot(x_grid, y_values, label=label)
    add_reference_line(y_label)

    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.title(title)
    plt.legend()
    plt.grid()
 
    Path(path).mkdir(parents=True, exist_ok=True)
    plt.savefig(
        os.path.join(path, save_filename(title) + ".png"),
        dpi=200,
        bbox_inches="tight"
    )
    plt.close()

def metric_folder(metric):
    """
    Generate a folder name for the given metric.
    """
    return "mse" if "mse" in metric else "variance"

# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

def plot_plots(
        *,
        q_values,
        q_range,
        epsilon_values,
        epsilon_range,
        chebyshev_degrees,
        Delta_values,
        metrics,
        each_plot,         
        path_for_plots
):
    """
    Generate all plots for the given parameters.
    """
    reports_by_degree, symbols = build_reports(chebyshev_degrees)

    q_symbol = symbols["q"]
    epsilon_symbol = symbols["epsilon"]
    Delta_symbol = symbols["Delta"]

    eps_grid = np.linspace(epsilon_range[0], epsilon_range[1], 300)
    q_grid = np.linspace(q_range[0], q_range[1], 300)

    for metric in metrics:
        y_label = METRIC_LABELS[metric]

        # 1) One plot per degree, curves by q, x = epsilon
        if "q_by_degree" in each_plot:
            for degree in chebyshev_degrees:
                for Delta_value in Delta_values:
                    y_data = curves_q_for_fixed_degree(
                        reports_by_degree=reports_by_degree,
                        degree=degree,
                        q_values=q_values,
                        metric=metric,
                        epsilon_symbol=epsilon_symbol,
                        eps_grid=eps_grid,
                        q_symbol=q_symbol,
                        base_subs={Delta_symbol: Delta_value},
                    )
                    title = (
                        f"{y_label} for Chebyshev degree {degree}, "
                        f"$\\Delta$ = {Delta_value}"
                    )
                    path = os.path.join(
                        path_for_plots, "q_by_degree", metric_folder(metric)
                    )
                    plot_curves(
                        x_label="epsilon",
                        y_label=y_label,
                        x_grid=eps_grid,
                        y_data=y_data,
                        title=title,
                        path=path,
                    )
        # 2) One plot per q, curves by degree, x = epsilon
        if "degree_by_q" in each_plot:
            for q_value in q_values:
                for Delta_value in Delta_values:
                    y_data = curves_degree_for_fixed_q(
                        reports_by_degree=reports_by_degree,
                        degree_values=chebyshev_degrees,
                        q_value=q_value,
                        metric=metric,
                        epsilon_symbol=epsilon_symbol,
                        eps_grid=eps_grid,
                        q_symbol=q_symbol,
                        base_subs={Delta_symbol: Delta_value},
                    )
                    title = f"{y_label} for q = {format_value(q_value)}, $\\Delta$ = {Delta_value}"
                    path = os.path.join(
                        path_for_plots, "degree_by_q", metric_folder(metric)
                    )
                    plot_curves(
                        x_label=f"$\\epsilon$",
                        y_label=y_label,
                        x_grid=eps_grid,
                        y_data=y_data,
                        title=title,
                        path=path,
                    )
        # 3) One plot per degree, curves by epsilon, x = q
        if "epsilon_by_degree" in each_plot:
            for degree in chebyshev_degrees:
                for Delta_value in Delta_values:
                    y_data = curves_epsilon_for_fixed_degree(
                        reports_by_degree=reports_by_degree,
                        degree=degree,
                        epsilon_values=epsilon_values,
                        metric=metric,
                        q_symbol=q_symbol,
                        q_grid=q_grid,
                        epsilon_symbol=epsilon_symbol,
                        base_subs={Delta_symbol: Delta_value},
                    )
                    title = (
                        f"{y_label} for Chebyshev degree {degree}, "
                        f"$\\Delta$ = {Delta_value}, curves by epsilon"
                    )
                    path = os.path.join(
                        path_for_plots, "epsilon_by_degree", metric_folder(metric)
                    )
                    plot_curves(
                        x_label="q",
                        y_label=y_label,
                        x_grid=q_grid,
                        y_data=y_data,
                        title=title,
                        path=path,
                    )