import sympy as sp
import numpy as np
import os

from dp_estimators import EstimatorSystem
from noise_models import LaplaceNoiseModel
from plotting.utility_plotting import format_value, metric_expr, evaluate_on_grid, plot_curves, metric_folder

METRIC_LABELS = {
    "variance_ratio": "Variance Ratio",
    "variance_relative": "Variance Relative",
    "mse_ratio": "MSE Ratio",
    "mse_relative": "MSE Relative"
}

#----------------------------------------------------------------------
# Symbolic Setup
#----------------------------------------------------------------------

def build_system():
    """
    Function initializes the EstimatorSystem with a Laplace noise model, using symbolic variables for Delta, epsilon, q, and X.
    This allows for symbolic analysis of the estimators and their properties as functions of these parameters. 
    Input: 
    - None (the symbolic variables are defined within the function)
    Output:
    - system: an instance of EstimatorSystem initialized with the Laplace noise model and symbolic variables
    - {"Delta": Delta, "epsilon": epsilon, "q": q, "X": X}: a dictionary of the symbolic variables used in the system.
    """
    Delta = sp.Symbol("Delta", real=True, positive=True)
    epsilon = sp.Symbol("epsilon", real=True, positive=True)
    q = sp.Symbol("q", real=True)
    X = sp.Symbol("X", real=True)

    system = EstimatorSystem(
        noise_model=LaplaceNoiseModel(delta=Delta, epsilon=epsilon),
        q=q,
        x=X
    )
    return system, {"Delta": Delta, "epsilon": epsilon, "q": q, "X": X}

def symbolic_chebyshev_reports(system, chebyshev_degrees):
    """
    Function takes an EstimatorSystem and a list of Chebyshev degrees, and computes 
    the comparison reports for the unbiased estimator corresponding to the Chebyshev 
    polynomial of each degree. reports_by_degree is the report returned by system.compare().
    Input:
    - system: an instance of EstimatorSystem, which contains the noise model and the symbolic variables
    - chebyshev_degrees: a list of integers representing the degrees of the 
        Chebyshev polynomials to analyze
    Output:
    - reports_by_degree: a dictionary mapping each degree n to the report 
    generated by system.compare() for the Chebyshev polynomial of degree n. 
    Each report contains the symbolic expressions for the variance and MSE 
    of the unbiased estimator corresponding to the Chebyshev polynomial 
    of that degree.
    """
    reports_by_degree = {}
    for n in chebyshev_degrees:
        f = sp.chebyshevt(n, system.q)
        report = system.compare(f=f)
        reports_by_degree[n] = report

    return reports_by_degree

def build_reports(chebyshev_degrees):
    """
    Function uses the build_system functions to initialize the 
    system with the specified symbolic variables, and the calls symbolic_chebyshev_reports
    to compute the reports for the specified Chebyshev degrees.
    It basically combines the system initialization and the report generation.
    Input:
    - chebyshev_degrees: a list of integers representing the degrees of the Chebyshev polynomials to analyze
    Output:
    - reports_by_degree: a dictionary mapping each degree n to the report generated by system.compare()
    - symbols: a dictionary of the symbolic variables used in the system
    """
    system, symbols = build_system()
    reports_by_degree = symbolic_chebyshev_reports(
        system=system,
        chebyshev_degrees=chebyshev_degrees
    )
    return reports_by_degree, symbols

# ----------------------------------------------------------------------
# Curve Builders
# ----------------------------------------------------------------------

def curves_q_for_fixed_degree(
        reports_by_degree, 
        degree, 
        q_values, 
        metric, 
        epsilon_symbol, 
        eps_grid, 
        q_symbol, 
        base_subs
):
    """
    One plot for a fixed degree.
    Curves vary by q.
    X-axis is epsilon.
    """
    out = {}
    expr = metric_expr(reports_by_degree, degree, metric)

    for q_value in q_values:
        subs = dict(base_subs) # make a copy of the base substitutions, to avoid modifying the original
        subs[q_symbol] = q_value
        label = f"q = {format_value(q_value)}"
        out[label] = evaluate_on_grid(expr, epsilon_symbol, eps_grid, subs)
    
    return out

def curves_degree_for_fixed_q(
        reports_by_degree, 
        degree_values, 
        q_value, 
        metric, 
        epsilon_symbol, 
        eps_grid, 
        q_symbol, 
        base_subs
):
    """
    One plot for a fixed q.
    Curves vary by degree.
    X-axis is epsilon.
    """
    out = {}
    subs = dict(base_subs) # make a copy of the base substitutions, to avoid modifying the original
    subs[q_symbol] = q_value

    for degree in degree_values:
        expr = metric_expr(reports_by_degree, degree, metric)
        label = f"Degree {format_value(degree)}"
        out[label] = evaluate_on_grid(expr, epsilon_symbol, eps_grid, subs)
    
    return out

def curves_epsilon_for_fixed_degree(
        reports_by_degree,
        degree, 
        epsilon_values, 
        metric, 
        q_symbol, 
        q_grid, 
        epsilon_symbol,
        base_subs
):
    """
    One plot for a fixed degree.
    Curves vary by epsilon.
    X-axis is q.
    """
    out = {}
    expr = metric_expr(reports_by_degree, degree, metric)

    for epsilon_value in epsilon_values:
        subs = dict(base_subs) # make a copy of the base substitutions, to avoid modifying the original
        subs[epsilon_symbol] = epsilon_value
        label = f"epsilon = {format_value(epsilon_value)}"
        out[label] = evaluate_on_grid(expr, q_symbol, q_grid, subs)
    
    return out

# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

def plot_plots(
        *,
        q_values,
        q_range,
        epsilon_values,
        epsilon_range,
        chebyshev_degrees,
        Delta_values,
        metrics,
        each_plot,         
        path_for_plots
):
    """
    Generate all plots for the given parameters.
    """
    reports_by_degree, symbols = build_reports(chebyshev_degrees)

    q_symbol = symbols["q"]
    epsilon_symbol = symbols["epsilon"]
    Delta_symbol = symbols["Delta"]

    eps_grid = np.linspace(epsilon_range[0], epsilon_range[1], 300)
    q_grid = np.linspace(q_range[0], q_range[1], 300)

    for metric in metrics:
        y_label = METRIC_LABELS[metric]

        # 1) One plot per degree, curves by q, x = epsilon
        if "q_by_degree" in each_plot:
            for degree in chebyshev_degrees:
                for Delta_value in Delta_values:
                    y_data = curves_q_for_fixed_degree(
                        reports_by_degree=reports_by_degree,
                        degree=degree,
                        q_values=q_values,
                        metric=metric,
                        epsilon_symbol=epsilon_symbol,
                        eps_grid=eps_grid,
                        q_symbol=q_symbol,
                        base_subs={Delta_symbol: Delta_value},
                    )
                    title = (
                        f"{y_label} for Chebyshev degree {degree}, "
                        f"$\\Delta$ = {Delta_value}"
                    )
                    save_path = os.path.join(
                        path_for_plots, "q_by_degree", metric_folder(metric)
                    )
                    plot_curves(
                        x_label="epsilon",
                        y_label=y_label,
                        x_grid=eps_grid,
                        y_data=y_data,
                        title=title,
                        save_path=save_path,
                    )
        # 2) One plot per q, curves by degree, x = epsilon
        if "degree_by_q" in each_plot:
            for q_value in q_values:
                for Delta_value in Delta_values:
                    y_data = curves_degree_for_fixed_q(
                        reports_by_degree=reports_by_degree,
                        degree_values=chebyshev_degrees,
                        q_value=q_value,
                        metric=metric,
                        epsilon_symbol=epsilon_symbol,
                        eps_grid=eps_grid,
                        q_symbol=q_symbol,
                        base_subs={Delta_symbol: Delta_value},
                    )
                    title = f"{y_label} for q = {format_value(q_value)}, $\\Delta$ = {Delta_value}"
                    save_path = os.path.join(
                        path_for_plots, "degree_by_q", metric_folder(metric)
                    )
                    plot_curves(
                        x_label=f"$\\epsilon$",
                        y_label=y_label,
                        x_grid=eps_grid,
                        y_data=y_data,
                        title=title,
                        save_path=save_path,
                    )
        # 3) One plot per degree, curves by epsilon, x = q
        if "epsilon_by_degree" in each_plot:
            for degree in chebyshev_degrees:
                for Delta_value in Delta_values:
                    y_data = curves_epsilon_for_fixed_degree(
                        reports_by_degree=reports_by_degree,
                        degree=degree,
                        epsilon_values=epsilon_values,
                        metric=metric,
                        q_symbol=q_symbol,
                        q_grid=q_grid,
                        epsilon_symbol=epsilon_symbol,
                        base_subs={Delta_symbol: Delta_value},
                    )
                    title = (
                        f"{y_label} for Chebyshev degree {degree}, "
                        f"$\\Delta$ = {Delta_value}, curves by epsilon"
                    )
                    save_path = os.path.join(
                        path_for_plots, "epsilon_by_degree", metric_folder(metric)
                    )
                    plot_curves(
                        x_label="q",
                        y_label=y_label,
                        x_grid=q_grid,
                        y_data=y_data,
                        title=title,
                        save_path=save_path,
                    )