from os import path

import sympy as sp
import numpy as np
import os

from dp_estimators import EstimatorSystem
from noise_models import LaplaceNoiseModel, GaussianNoiseModel
from plotting.utility_plotting import format_value, metric_expr, evaluate_on_grid, plot_curves, metric_folder 
from dp_calibration.SigmaFromEpsilon import SigmaFromEpsilon

METRIC_LABELS = {
    "variance_ratio": "Variance Ratio",
    "variance_relative": "Variance Relative",
    "mse_ratio": "MSE Ratio",
    "mse_relative": "MSE Relative"
}

#----------------------------------------------------------------------
# Symbolic Setup
#----------------------------------------------------------------------
def build_system(noise_model="laplace"):
    """
    Build the EstimatorSystem with the desired noise models and symbols. 
    Input: None
    Output: Two tuples (system, symbols), where
    - system is an instance of EstimatorSystem, initialized with the desired noise
      model and symbols
    - symbols is a dictionary of sympy symbols used in the system
    """
    q = sp.symbols("q", positive=True, real=True)
    X = sp.symbols("X", positive=True, real=True)

    if noise_model == "laplace":
        Delta = sp.symbols("Delta", positive=True, real=True)
        epsilon = sp.symbols("epsilon", positive=True, real=True)

        system = EstimatorSystem(
            noise_model=LaplaceNoiseModel(Delta=Delta, epsilon=epsilon),
            q=q,
            x=X
        )
        symbols = {"Delta": Delta, "epsilon": epsilon, "q": system.q, "X": system.x}

    elif noise_model == "gaussian":
        sigma = sp.symbols("sigma", positive=True, real=True)

        system = EstimatorSystem(
            noise_model=GaussianNoiseModel(sigma=sigma),
            q=q,
            x=X
        )
        symbols = {"sigma": sigma, "q": system.q, "X": system.x}

    else:
        raise ValueError(f"Unsupported noise model: {noise_model}")
    
    return system, symbols

def symbolic_poly_reports(system, polynomials):
    """
    Generate symbolic reports for a list of polynomials, using the given EstimatorSystem.
    Input:
    - system: an instance of EstimatorSystem, initialized with the desired noise
      model and symbols
    - polynomials: a list of tuples (name, f), where name is a string identifier 
      for the polynomial, and f is a sympy expression for the polynomial function of q.
    Output:
    - A dictionary mapping each polynomial name to its symbolic report 
      generated by the system's compare method
    """
    reports = {}
    for name, f in polynomials.items():

        # The following is to avoid issues with sympy not recognizing the symbol
        # "q" in the symbolic expressions,whic can happen with wrong symbols. 
        f = sp.sympify(f)
        # Replace any symbol named "q" with system.q.
        for sym in f.free_symbols:
            if sym.name == "q":
                f = f.subs(sym, system.q)

        reports[name] = system.compare(f=f)
    return reports

def build_reports(polynomials):
    """
    Build the EstimatorSystem's and generate symbolic reports for the given polynomials.
    Input:
    - polynomials: a list of tuples (name, f), where name is a string identifier 
      for the polynomial, and f is a sympy expression for the polynomial function of q.
    Output:
    - A dictionary mapping the noise models, "laplace" and "gaussian", to their respective 
        dictionaries of symbolic reports and their symbols. Specifically, the output is a tuple of two dictionaries:
        - The first dictionary maps each noise model ("laplace" and "gaussian") to its respective dictionary of symbolic report.
        - The second dictionary maps each noise model to its respective dictionary of sympy symbols used in the system.

    """
    laplace_system, laplace_symbols = build_system(noise_model="laplace")
    gaussian_system, gaussian_symbols = build_system(noise_model="gaussian")

    laplace_reports = symbolic_poly_reports(laplace_system, polynomials)
    gaussian_reports = symbolic_poly_reports(gaussian_system, polynomials)

    return {
        "laplace": laplace_reports,
        "gaussian": gaussian_reports
    }, {
        "laplace": laplace_symbols,
        "gaussian": gaussian_symbols
    }

def base_subs_for_noise(
        noise_dist, 
        symbols, 
        *, 
        q_value=None, 
        Delta_value=None, 
        epsilon_value=None,
        delta_value=None
):
    """
    Build substitution dicts for Gaussian or Laplace noise. 
    For Gaussian, epsilon is introduced via the relation: 
        sigma = sqrt(2) * Delta / epsilon, 
    as it is not an inherent parameter ot this noise distribution. 

    If epsilon_value is None, sigma remains symbolic in epsilon
    (for plotting over epsilon on the x-axis). 

    Input: 
    - noise_dist: a string, either "laplace or "gaussian", 
    - symbols: the dictionary of symbols ordered by noise distribution, 
      as returned by the build_reports function, i.e., symbols_by_noise_dist
    - q_value: a specific value of q to substitute (if not None)
    - Delta_value: a specific value of Delta to substitute (if not None)
    - epsilon_value: a specific value of epsilon to substitute (if not None)
    Output:
    - A dictionary of substitutions to apply to the symbolic expressions for the given noise distribution.
    """
    # ----- Laplace -----
    if noise_dist == "laplace":
        subs = {}
        if q_value is not None:
            subs[symbols[noise_dist]["q"]] = q_value
        if Delta_value is not None:
            subs[symbols[noise_dist]["Delta"]] = Delta_value
        if epsilon_value is not None:            
            subs[symbols[noise_dist]["epsilon"]] = epsilon_value

    # ----- Gaussian -----
    elif noise_dist == "gaussian":
        subs = {}
        if q_value is not None:
            subs[symbols[noise_dist]["q"]] = q_value

        if Delta_value is not None:
            # epsilon is symbolic and symbolic report construct id being done
            if epsilon_value is None:
                # the value epsilon is NOT inherent in Gaussian dist
                epsilon_symbol = symbols["laplace"]["epsilon"]
                subs[symbols[noise_dist]["sigma"]] = SigmaFromEpsilon(
                    epsilon_symbol,
                    delta_value,  # a very small delta to approximate pure DP
                    Delta_value
                )
            # epsilon is numeric (float, int, Rational, etc)
            else:
                 # turn the value of epsilon into a float
                 # to ensure it can be passed to the numerical func
                 eps_num = float(epsilon_value)
                 sigma_val = SigmaFromEpsilon.numeric(
                    eps_num,
                    delta_value,  # a very small delta to approximate pure DP
                    float(Delta_value))
                 subs[symbols[noise_dist]["sigma"]] = sigma_val
    else:
        raise ValueError(f"Unsupported noise distribution: {noise_dist}")
    return subs

# ----------------------------------------------------------------------
# Curve Builders
# ----------------------------------------------------------------------
def curves_q_for_poly(
        reports, # reports by noise distribution
        symbols, # symbls by noise distribution
        name,
        metric,
        q_values, 
        Delta_value,
        eps_grid, 
        delta_value
):
    """
    Build curves of the given metric. 
    One plot for each polynomial, 
    curves vary by q values,  
    plotted over epsilon on the x-axis, 
    and with fixed Delta, 
    for both noise distributions.

    OBS! This function only gets a single polynomial name as input, so this is meant to be
    called in a loop over polynomial names, to generate one plot per polynomial.

    Input:
    - reports: a dictionary mapping noise distributions to their respective symbolic reports, as returned by build_reports
    - symbols: a dictionary mapping noise distributions to their respective dictionaries of sympy symbols, as returned by build_reports
    - name: the name of the polynomial to plot (must be a key in the reports)
    - metric: the name of the metric to plot (e.g., "variance_ratio", "mse_relative", etc.)
    - q_values: a list of specific q values to plot
    - Delta_value: a specific value of Delta to use in the plots
    - eps_grid: a numpy array of epsilon values to evaluate the curves on
    Output:
    """
    out = {}
    
    for noise_dist in ["laplace", "gaussian"]:
        expr = metric_expr(
            reports_by_label=reports[noise_dist],
            label=name,
            metric=metric
        )

        for q_value in q_values:
            subs = base_subs_for_noise(
                noise_dist=noise_dist, 
                symbols=symbols, 
                q_value=q_value, 
                Delta_value=Delta_value,
                delta_value=delta_value
            )
            label = f"{noise_dist.capitalize()} noise, q={format_value(q_value)}"
            out[label] = evaluate_on_grid(expr, 
                                          # always using epsilon from laplace, as epsilon does
                                          # NOT exist for Gaussian noise, but is introduced via 
                                          # the relation sigma = sqrt(2) * Delta / epsilon
                                          symbols["laplace"]["epsilon"],
                                          eps_grid, 
                                          subs
                                          )
    return out

    

def curves_poly_for_q(
        reports, # reports by noise distribution
        symbols, # symbls by noise distribution
        names,
        metric,
        q_value, 
        Delta_value,
        eps_grid,
        delta_value
):
    """ 
    Build curves of the given metric, 
    one plot for each q value, 
    curves vary by polynomial, 
    plotted over epsilon on the x-axis, 
    and with fixed Delta,
    for both noise distributions. 

    OBS! This function only gets a single q_value as input, so this is meant to be 
    called in a loop over q_values, to generate one plot per q value.

    Input:
    - reports: a dictionary mapping noise distributions to their respective symbolic reports, as returned by build_reports
    - symbols: a dictionary mapping noise distributions to their respective dictionaries of sympy symbols, as returned by build_reports
    - names: a list of polynomial names to plot (must be keys in the reports)
    - metric: the name of the metric to plot (e.g., "variance_ratio", "mse_relative", etc.)
    - q_value: a specific value of q to use in the plots
    - Delta_value: a specific value of Delta to use in the plots
    - eps_grid: a numpy array of epsilon values to evaluate the curves on
    Output:
    """
    out = {}
    for noise_dist in ["laplace", "gaussian"]:
        for name in names:
            expr = metric_expr(
                reports_by_label=reports[noise_dist],
                label=name,
                metric=metric
            )

            subs = base_subs_for_noise(
                noise_dist=noise_dist, 
                symbols=symbols, 
                q_value=q_value, 
                Delta_value=Delta_value,
                delta_value=delta_value
            )

            label = f"{noise_dist.capitalize()}, {format_value(name)}"
            out[label] = evaluate_on_grid(expr, 
                                          # always using epsilon from laplace, as epsilon does
                                          # NOT exist for Gaussian noise, but is introduced via 
                                          # the relation sigma = sqrt(2) * Delta / epsilon
                                          symbols["laplace"]["epsilon"], 
                                          eps_grid, 
                                          subs
                                          )
    return out

def curves_epsilon_for_poly(
        reports, # reports by noise distribution 
        symbols, # symbls by noise distribution
        name,
        metric,
        epsilon_values, 
        Delta_value,
        q_grid,
        delta_value
):
    """
    Build curves of the given metric,
    one plot for each polynomial,
    curves vary by epsilon values,
    plotted over q on the x-axis,
    and with fixed Delta,
    for both noise distributions.

    OBS! This function only gets a single polynomial name as input, so this is meant to be
    called in a loop over polynomial names, to generate one plot per polynomial.
    """
    out = {}
    
    
    for noise_dist in ["laplace", "gaussian"]:
        expr = metric_expr(
            reports_by_label=reports[noise_dist],
            label=name,
            metric=metric
        )

        for epsilon_value in epsilon_values:
            subs = base_subs_for_noise(
                noise_dist=noise_dist,
                symbols=symbols,
                epsilon_value=epsilon_value,
                Delta_value=Delta_value,
                delta_value=delta_value
            )
            label = f"{noise_dist.capitalize()} noise, ε={format_value(epsilon_value)}"
            out[label] = evaluate_on_grid(expr, 
                                          symbols[noise_dist]["q"], 
                                          q_grid, 
                                          subs
                                          )
    return out

# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

def plot_plots(
    *,
    q_values,
    q_range,
    epsilon_values,
    epsilon_range,
    polynomials,
    Delta_values,
    delta_value,
    metrics,
    each_plot,
    path_for_plots
):
    """
    Main function to generate and save the desired plots.
    Input:
    - q_values: a list of specific q values to plot (if plotting over epsilon)
    - q_range: a tuple (q_min, q_max) specifying the range of q values to plot (if plotting over q)
    - epsilon_values: a list of specific epsilon values to plot (if plotting over q)
    - epsilon_range: a tuple (epsilon_min, epsilon_max) specifying the range of epsilon values to plot (if plotting over epsilon)
    - polynomials: a dictionary mapping polynomial names to their sympy expressions
    - Delta_values: a list of specific Delta values to use in the plots
    - delta_value: a specific value of delta to use in the Gaussian noise calibration (if needed)
    - metrics: a list of metric names to plot (e.g., "variance_ratio", "mse_relative", etc.)
    - each_plot: a list of strings indicating how to group curves in each plot (e.g., "q_by_poly", "poly_by_q", etc.)
    - path_for_plots: the base directory path where the generated plots should be saved
    Output:
    - The function generates and saves the specified plots according to the input parameters.
    """

    # Build symbolic reports for both noise models
    reports_by_noise_dist, symbols_by_noise_dist = build_reports(polynomials)

    eps_grid = np.linspace(epsilon_range[0], epsilon_range[1], 300)
    q_grid = np.linspace(q_range[0], q_range[1], 300)

    names = list(polynomials.keys())

    for metric in metrics:
        y_label = METRIC_LABELS[metric]

        # One plot per polynomial, curves vary by q values and noise model, x = eps
        if "q_by_poly" in each_plot:
            for name in names:
                for Delta_value in Delta_values:
                    curves = curves_q_for_poly(
                        reports=reports_by_noise_dist,
                        symbols=symbols_by_noise_dist,
                        name=name,
                        metric=metric,
                        q_values=q_values,
                        Delta_value=Delta_value,
                        eps_grid=eps_grid, 
                        delta_value=delta_value
                    )
                    title = (
                        f"{y_label} vs ε, for {format_value(name)}, " 
                        f"Δ = {format_value(Delta_value)}"
                    )
                    save_path = os.path.join(
                        path_for_plots, 
                        "q_by_poly",
                        metric_folder(metric)
                    )
                    " x_label, y_label, x_grid, y_data, title=None, save_path=None"
                    plot_curves(x_label="ε", 
                                y_label=y_label,
                                x_grid=eps_grid,
                                y_data=curves,
                                title=title,
                                save_path=save_path
                    )
        # One plot per q value, curves vary by polynomial and noise model, x = eps
        if "poly_by_q" in each_plot:
            for q_value in q_values:
                for Delta_value in Delta_values:
                    curves = curves_poly_for_q(
                        reports=reports_by_noise_dist,
                        symbols=symbols_by_noise_dist,
                        names=names,
                        metric=metric,
                        q_value=q_value,
                        Delta_value=Delta_value,
                        eps_grid=eps_grid,
                        delta_value=delta_value
                    )
                    title = (
                        f"{y_label} vs ε, for q = {format_value(q_value)}, "
                        f"Δ = {format_value(Delta_value)}"
                    )
                    save_path = os.path.join(
                        path_for_plots, 
                        "poly_by_q", 
                        metric_folder(metric)
                    )
                    plot_curves(x_label="ε", 
                                y_label=y_label, 
                                x_grid=eps_grid, 
                                y_data=curves, 
                                title=title, 
                                save_path=save_path
                    )
        # One plot per polynomial, curves vary by epsilon values and noise model, x = q
        if "epsilon_by_poly" in each_plot:
            for name in names:
                for Delta_value in Delta_values:
                    curves = curves_epsilon_for_poly(
                        reports=reports_by_noise_dist,
                        symbols=symbols_by_noise_dist,
                        name=name,
                        metric=metric,
                        epsilon_values=epsilon_values,
                        Delta_value=Delta_value,
                        q_grid=q_grid,
                        delta_value=delta_value
                    )
                    title = (
                        f"{y_label} vs ε, for {format_value(name)}, "
                        f"Δ = {format_value(Delta_value)}"
                    )
                    save_path = os.path.join(
                        path_for_plots, 
                        "epsilon_by_poly", 
                        metric_folder(metric)
                    )
                    plot_curves(x_label="q", 
                                y_label=y_label, 
                                x_grid=q_grid, 
                                y_data=curves, 
                                title=title, 
                                save_path=save_path
                    )